### ISSUE TITLE
Seems a similar module

### ISSUE THREAD

**Issue by wangdaning** [yangzhaofeng/ctenabler#1]
Hello, 
I mean that in no bad way, just the module seems like what I pieced together from various places for the Pixel 3/xl. You can see it in my git repo. You seem to be better at coding it, I still had to do a delete of files, might be a Pixel 3 thing I suppose, but you could incorporate my module bits into yours. Seems getting CTE is not more difficult than getting CM and CU, too.

**Comment by yangzhaofeng** [comment]
Some devices (like Pixel 4) may not contain these Chinese mbn files so it is necessary to copy them from another device. 

But on the other hand, not only copying the mbn files but also modifying `mbn_sw.txt` is also a good thought. Would you also like to share your Chinese mbn file from your Pixel 3 if possible?

**Comment by wangdaning** [comment]
I would share, but it is a large file. The files are all located in the factory vendor.img. Is it not the same with the Pixel 4? On the Pixel 3 it is that the .mbn files are there, but the mbn_sw.txt fails to point to them.

**Comment by wangdaning** [comment]
Thought they would be larger, here are the files from I think February factory image.
[Pixel 3 mbn Feb.zip](https://github.com/yangzhaofeng/ctenabler/files/4735340/Pixel.3.mbn.Feb.zip)

**Comment by yangzhaofeng** [comment]
It seems that the mbn files on Pixel 3 does not work on Pixel 4.

**Comment by wangdaning** [comment]
I am guessing the Pixel 4 also does not have the Chinese mbn files in ...\mcfg_sw\generic\
Anyway, just noticed your module and thought I could share some ideas. Good luck with it. Feel free to close this.
