### ISSUE TITLE
pixel4xl安装ctenabler模块没用

### ISSUE THREAD

**Issue by cuihua0** [yangzhaofeng/ctenabler#7]
使用的各种版本
android 11
Magisk-v23.0.apk
ctenabler-0.0.4.zip
voenabler-v1.8.zip

已经使用指令
adb shell settings put global captive_portal_https_url https://www.google.cn/generate_204
adb shell settings put global captive_portal_http_url http://www.google.cn/generate_204

wifi信号有了，电信卡能读取出来，但是没有信号。
选择网络chn-ct无法连接
lte，3g，2g都不能用

**Comment by yangzhaofeng** [comment]
你的pixel 4 xl 是在哪購買的？目前北美版之外的國際版硬件不支持中國電信

**Comment by cuihua0** [comment]
你好，我购买的台湾制造商做的欧版可解锁。试了下，我用安卓10版本装可以，11不行
